ads-link: ""
new-forms-link: ""

telegram-bot-token: ""

publicidad:
  period: 900
  format: "&8[&7Publicidad&8] &b{message}"
  no-ads-available: "&8[&7Publicidad&8] &bNo hay ningún anuncio disponible ahora mismo."
  not-found: "&8[&7Publicidad&8] &bNo se ha encontrado ningún anuncio de {player}"
  usage: "&8[&7Publicidad&8] &bUso: /sendad [nick]"

staffchat-channel: "-1001152644239"
adminchat-channel: "-1001337303858"
eventoschat-channel: "-1001423341152"
#telegram-channel: "-431045578"

formularios:
  new-form: "&f[&7A51&f] &bNuevo &eformulario &bpendiente de &e{players}"
  voy: "&f[&7A51&f] &b{user} &eestá revisando el último formulario enviado."
  telegram-new-form: "Nuevo formulario pendiente de {players}"
  telegram-voy: "*{user}* está revisando el último formulario enviado."

chat:
  minecraft-modchannel: "&f[&3StaffTelegram&f] &a{user}&f: &b{message}"
  telegram-modchannel: "*{user}*: {message}"
  minecraft-adminchannel: "&f[&3AdminTelegram&f] &a{user}&f: &b{message}"
  telegram-adminchannel: "*{user}*: {message}"
  minecraft-eventoschannel: "&f[&4EventosTelegram&f] &c{user}&f: &b{message}"
  telegram-eventoschannel: "*{user}*: {message}"
  muted-chat: "&f[&3Telegram&f] &bHas &csilenciado&b todas las conversaciones de Telegram."
  unmuted-chat: "&f[&3Telegram&f] &bHas &adejado de silenciar&b todas las conversaciones de Telegram."
  telegram-chat-not-allowed: "Este chat no tiene permitido el uso de este comando."
  telegram-alert-visitor-in-game: "El nuevo usuario *{user}* se acaba de conectar al servidor."
  minecraft-not-enough-args: "&f[&3Telegram&f] &bNo puedes enviar un mensaje vacio."

protocol:
  name: 'Edoras 1.16.4'
  version:
    - 754 # 1.16.4
  do-not-kick:
    - 340 # 1.12.2
  kick-message: "¡Versión incorrecta!.newline.Conéctate usando la versión Minecraft 1.16.4"